/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package etl;

import org.testng.annotations.*;
import static org.testng.Assert.*;

import etl.Main;

public class MainTest {
    @Test public void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
